// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { log } from "./log.js";
import { render } from "./render.js";
import { spinner } from "./spinner.js";

export const Statusbar = {
    log,
    render,
    spinner,
}
