// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $all } from "./$all.js";
import { $diff } from "./$diff.js";
import { $staged } from "./$staged.js";
import { $unstaged } from "./$unstaged.js";
import { diff } from "./diff.js";
import { fetch } from "./fetch.js";
import { fetchDiff } from "./fetchDiff.js";
import { isOnStatus } from "./isOnStatus.js";
import { list } from "./list.js";
import { render } from "./render.js";
import { status } from "./status.js";
import { Status } from "./types.js";
import { toggle } from "./toggle.js";

declare namespace WorkingCopy {
    export {
        $all,
        $diff,
        $staged,
        $unstaged,
        diff,
        fetch,
        fetchDiff,
        isOnStatus,
        list,
        render,
        status,
        toggle,
    }
}

export {
    WorkingCopy,
    Status,
}
