// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { createList } from "./createList.js";
import { discard } from "./discard.js";
import { parse } from "./parse.js";
import { parseFile } from "./parseFile.js";
import { toggle } from "./toggle.js";

type Diff = DiffFile[]

type DiffFile = {
    content: string
    header: string[]
    hunks: DiffHunk[]
    type: "file"
}

type DiffHunk = {
    changes: DiffLine[]
    content: string
    file: DiffFile
    type: "hunk"
}

type DiffLine = {
    content: string
    file: DiffFile
    hunk: DiffHunk
    type: "addition" | "deletion" | "context"
}

declare namespace Diff {
    export {
        createList,
        discard,
        parse,
        parseFile,
        toggle,
    }
}

export {
    Diff,
    DiffFile,
    DiffHunk,
    DiffLine,
}
