// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { createList } from "./createList.js";
import { discard } from "./discard.js";
import { parse } from "./parse.js";
import { parseFile } from "./parseFile.js";
import { toggle } from "./toggle.js";

export const Diff = {
    createList,
    discard,
    parse,
    parseFile,
    toggle,
}
