// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $commits } from "./$commits.js";
import { $current } from "./$current.js";
import { $diff } from "./$diff.js";
import { $local } from "./$local.js";
import { $remote } from "./$remote.js";
import { Branch } from "./types.js";
import { commit } from "./commit.js";
import { create } from "./create.js";
import { diff } from "./diff.js";
import { fetch } from "./fetch.js";
import { fetchCommits } from "./fetchCommits.js";
import { fetchDiff } from "./fetchDiff.js";
import { isOnCommit } from "./isOnCommit.js";
import { list } from "./list.js";
import { LocalBranch } from "./types.js";
import { RemoteBranch } from "./types.js";
import { render } from "./render.js";

declare namespace Branches {
    export {
        $commits,
        $current,
        $diff,
        $local,
        $remote,
        commit,
        create,
        diff,
        fetch,
        fetchCommits,
        fetchDiff,
        isOnCommit,
        list,
        render,
    }
}

export {
    Branches,
    Branch,
    LocalBranch,
    RemoteBranch,
}
