// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { branch } from "./branch.js";
import { isOnBranch } from "./isOnBranch.js";
import { isOnHistory } from "./isOnHistory.js";
import { isOnLocalBranch } from "./isOnLocalBranch.js";
import { isOnRemoteBranch } from "./isOnRemoteBranch.js";
import { isOnStashes } from "./isOnStashes.js";
import { isOnTag } from "./isOnTag.js";
import { isOnWorkingCopy } from "./isOnWorkingCopy.js";
import { list } from "./list.js";
import { render } from "./render.js";

declare namespace Sidebar {
    export {
        branch,
        isOnBranch,
        isOnHistory,
        isOnLocalBranch,
        isOnRemoteBranch,
        isOnStashes,
        isOnTag,
        isOnWorkingCopy,
        list,
        render,
    }
}

export {
    Sidebar,
}
