// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $all } from "./$all.js";
import { $diff } from "./$diff.js";
import { diff } from "./diff.js";
import { fetch } from "./fetch.js";
import { fetchDiff } from "./fetchDiff.js";
import { isOnStash } from "./isOnStash.js";
import { list } from "./list.js";
import { render } from "./render.js";
import { stash } from "./stash.js";
import { Stash } from "./types.js";

declare namespace Stashes {
    export {
        $all,
        $diff,
        diff,
        fetch,
        fetchDiff,
        isOnStash,
        list,
        render,
        stash,
    }
}

export {
    Stashes,
    Stash,
}
